### ISSUE TITLE
Force fallback mode with a environment variable?

### ISSUE THREAD

**Issue by GrabbenD** [KnapsackPro/knapsack-pro-core-js#24]
We're currently running different scopes of tests for our Cypress, one being for local development where we don't want to connect to a external API. Currently this outputs errors about the API not being reachable and we'd like to ask if it would be possible to have a environment variable that directly skips to fallback mode and doesn't generate errors.

Thank you for the effort in this project!

**Comment by ArturT** [comment]
Do you want to still send recorded tests timing to Knapsack Pro API after the tests are executed on a parallel node?

What's your account at https://knapsackpro.com ? I can review your CI builds. You can [email me](https://knapsackpro.com/contact) with your email you used to signed up.

**Comment by GrabbenD** [comment]
Hey @ArturT!

Thanks for asking, the recordings can be discarded since it's only for local development and production results aren't being recorded to any dashboard just yet. We're in progress of migrating from CircleCI to Jenkins and Cypress Parallel tests (our full pipeline isn't working yet due to some bad practices that makes the test depend on each other and with parallel they always fail).

Regards.

**Comment by ArturT** [comment]
In order to force Knapsack Pro to start in the Fallback Mode you can set fake API endpoint:

```
KNAPSACK_PRO_ENDPOINT=https://fake.api.knapsackpro.com
```

You can change the log level if this is annoying:
https://github.com/KnapsackPro/knapsack-pro-core-js#how-to-change-log-level

I recommend to [sign up an account with unlimited trial](https://knapsackpro.com/pricing) and create a bash script to quickly start Knapsack Pro in the shell. This is how I test it in development:

https://github.com/KnapsackPro/cypress-example-kitchensink/blob/855f53351e6ba1e494e874434c47d00336a4d965/bin/knapsack_pro_cypress_test_file_pattern#L3

You could use it till you solve a problem with the tests depending on each other.

**Comment by GrabbenD** [comment]
That's our current approach and it works alright but ultimately the best solution would be if you could force fallback with a parameter or similar.

**Comment by ArturT** [comment]
Is there any technical reason why you don't want to use Knapsack Pro API to split tests or it's just the fact it's paid solution?

I'm trying to deliver real value to users and the best way to validate that something is really needed is people paying for it. I'm trying to see common patterns and repeating requests from paying users to ensure I add features that matter for them. Thanks to that I can keep the solution thin and focus on something that will help growth and allow Knapsack Pro project to be supported by the community. 

If there is any blocker on your side that prevents you from using Knapsack Pro API I'd like to learn more and maybe I will be able to help. 

If you look just for free solution that's totally fine. You can fork the repo and adjust to your needs if that works better for you.

**Comment by GrabbenD** [comment]
Hey again @ArturT!

We're currently not looking into storing any of the recordings nor does our developers have the time to review those since our product is still in prototype stage which means the code changes quickly and thus for now having such dashboard is a overkill for the scope of our work, time and budget. Your project is beyond what we could ask for and if you feel like the feature I'm proposing is counterintuitive then feel free to disregard it.

Regards.

**Comment by ArturT** [comment]
@xRiot Thanks for the info. I'm closing this feature request then.

If this would help you at the current stage of your company I can set for you a free plan at https://knapsackpro.com I'd like to help your company in the long run. I know how hard it is to start a company so would be great to help you in this process.
